-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [verified_ledger]
import Aeneas
set_option linter.style.nameCheck false
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace verified_ledger

/-- [verified_ledger::sum_from]:
    Source: 'src/lib.rs', lines 17:0-23:1
    Visibility: public -/
def sum_from (balances : Slice Std.U64) (i : Std.Usize) : Result Std.U128 := do
  let i1 := Slice.len balances
  if i >= i1
  then ok 0#u128
  else
    let i2 ← Slice.index_usize balances i
    let i3 ← lift (UScalar.cast .U128 i2)
    let i4 ← i + 1#usize
    let i5 ← sum_from balances i4
    i3 + i5
partial_fixpoint

/-- [verified_ledger::sum_balances]:
    Source: 'src/lib.rs', lines 25:0-27:1
    Visibility: public -/
def sum_balances (balances : Slice Std.U64) : Result Std.U128 := do
  sum_from balances 0#usize

/-- [verified_ledger::Ledger]
    Source: 'src/lib.rs', lines 30:0-33:1
    Visibility: public -/
structure Ledger where
  balances : alloc.vec.Vec Std.U64
  total : Std.U128

/-- [verified_ledger::{impl core::fmt::Debug for verified_ledger::Ledger}::fmt]:
    Source: 'src/lib.rs', lines 29:9-29:14
    Visibility: public -/
def Ledger.Insts.CoreFmtDebug.fmt
  (self : Ledger) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn := Dyn.mk _ (core.fmt.DebugVec core.fmt.DebugU64) self.balances
  let dyn1 := Dyn.mk _ (core.fmt.DebugShared core.fmt.DebugU128) self.total
  core.fmt.Formatter.debug_struct_field2_finish f (toStr "Ledger") (toStr
    "balances") dyn (toStr "total") dyn1

/-- Trait implementation: [verified_ledger::{impl core::fmt::Debug for verified_ledger::Ledger}]
    Source: 'src/lib.rs', lines 29:9-29:14 -/
@[reducible]
def Ledger.Insts.CoreFmtDebug : core.fmt.Debug Ledger := {
  fmt := Ledger.Insts.CoreFmtDebug.fmt
}

/-- [verified_ledger::{impl core::clone::Clone for verified_ledger::Ledger}::clone]:
    Source: 'src/lib.rs', lines 29:16-29:21
    Visibility: public -/
def Ledger.Insts.CoreCloneClone.clone (self : Ledger) : Result Ledger := do
  let v ← alloc.vec.CloneVec.clone core.clone.CloneU64 self.balances
  let i ← lift (core.clone.impls.CloneU128.clone self.total)
  ok { balances := v, total := i }

/-- Trait implementation: [verified_ledger::{impl core::clone::Clone for verified_ledger::Ledger}]
    Source: 'src/lib.rs', lines 29:16-29:21 -/
@[reducible]
def Ledger.Insts.CoreCloneClone : core.clone.Clone Ledger := {
  clone := Ledger.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [verified_ledger::{impl core::marker::StructuralPartialEq for verified_ledger::Ledger}]
    Source: 'src/lib.rs', lines 29:23-29:32 -/
@[reducible]
def Ledger.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq Ledger := {
}

/-- [verified_ledger::{impl core::cmp::PartialEq<verified_ledger::Ledger> for verified_ledger::Ledger}::eq]:
    Source: 'src/lib.rs', lines 29:23-29:32
    Visibility: public -/
def Ledger.Insts.CoreCmpPartialEqLedger.eq
  (self : Ledger) (other : Ledger) : Result Bool := do
  if self.total = other.total
  then
    alloc.vec.partial_eq.PartialEqVec.eq core.cmp.PartialEqU64 self.balances
      other.balances
  else ok false

/-- Trait implementation: [verified_ledger::{impl core::cmp::PartialEq<verified_ledger::Ledger> for verified_ledger::Ledger}]
    Source: 'src/lib.rs', lines 29:23-29:32 -/
@[reducible]
def Ledger.Insts.CoreCmpPartialEqLedger : core.cmp.PartialEq Ledger Ledger := {
  eq := Ledger.Insts.CoreCmpPartialEqLedger.eq
}

/-- [verified_ledger::{impl core::cmp::Eq for verified_ledger::Ledger}::assert_fields_are_eq]:
    Source: 'src/lib.rs', lines 29:34-29:36
    Visibility: public -/
def Ledger.Insts.CoreCmpEq.assert_fields_are_eq
  (self : Ledger) : Result Unit := do
  ok ()

/-- Trait implementation: [verified_ledger::{impl core::cmp::Eq for verified_ledger::Ledger}]
    Source: 'src/lib.rs', lines 29:34-29:36 -/
@[reducible]
def Ledger.Insts.CoreCmpEq : core.cmp.Eq Ledger := {
  partialEqInst := Ledger.Insts.CoreCmpPartialEqLedger
  assert_fields_are_eq := Ledger.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [verified_ledger::LedgerError]
    Source: 'src/lib.rs', lines 36:0-40:1
    Visibility: public -/
@[discriminant isize]
inductive LedgerError where
| NoSuchAccount : LedgerError
| InsufficientFunds : LedgerError
| BalanceOverflow : LedgerError

/-- [verified_ledger::{impl core::fmt::Debug for verified_ledger::LedgerError}::fmt]:
    Source: 'src/lib.rs', lines 35:9-35:14
    Visibility: public -/
def LedgerError.Insts.CoreFmtDebug.fmt
  (self : LedgerError) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  match self with
  | LedgerError.NoSuchAccount =>
    core.fmt.Formatter.write_str f (toStr "NoSuchAccount")
  | LedgerError.InsufficientFunds =>
    core.fmt.Formatter.write_str f (toStr "InsufficientFunds")
  | LedgerError.BalanceOverflow =>
    core.fmt.Formatter.write_str f (toStr "BalanceOverflow")

/-- Trait implementation: [verified_ledger::{impl core::fmt::Debug for verified_ledger::LedgerError}]
    Source: 'src/lib.rs', lines 35:9-35:14 -/
@[reducible]
def LedgerError.Insts.CoreFmtDebug : core.fmt.Debug LedgerError := {
  fmt := LedgerError.Insts.CoreFmtDebug.fmt
}

/-- [verified_ledger::{impl core::clone::Clone for verified_ledger::LedgerError}::clone]:
    Source: 'src/lib.rs', lines 35:16-35:21
    Visibility: public -/
def LedgerError.Insts.CoreCloneClone.clone
  (self : LedgerError) : Result LedgerError := do
  ok self

/-- Trait implementation: [verified_ledger::{impl core::clone::Clone for verified_ledger::LedgerError}]
    Source: 'src/lib.rs', lines 35:16-35:21 -/
@[reducible]
def LedgerError.Insts.CoreCloneClone : core.clone.Clone LedgerError := {
  clone := LedgerError.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [verified_ledger::{impl core::marker::Copy for verified_ledger::LedgerError}]
    Source: 'src/lib.rs', lines 35:23-35:27 -/
@[reducible]
def LedgerError.Insts.CoreMarkerCopy : core.marker.Copy LedgerError := {
  cloneInst := LedgerError.Insts.CoreCloneClone
}

/-- Trait implementation: [verified_ledger::{impl core::marker::StructuralPartialEq for verified_ledger::LedgerError}]
    Source: 'src/lib.rs', lines 35:29-35:38 -/
@[reducible]
def LedgerError.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq LedgerError := {
}

/-- [verified_ledger::{impl core::cmp::PartialEq<verified_ledger::LedgerError> for verified_ledger::LedgerError}::eq]:
    Source: 'src/lib.rs', lines 35:29-35:38
    Visibility: public -/
def LedgerError.Insts.CoreCmpPartialEqLedgerError.eq
  (self : LedgerError) (other : LedgerError) : Result Bool := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  ok (self1 = other1)

/-- Trait implementation: [verified_ledger::{impl core::cmp::PartialEq<verified_ledger::LedgerError> for verified_ledger::LedgerError}]
    Source: 'src/lib.rs', lines 35:29-35:38 -/
@[reducible]
def LedgerError.Insts.CoreCmpPartialEqLedgerError : core.cmp.PartialEq
  LedgerError LedgerError := {
  eq := LedgerError.Insts.CoreCmpPartialEqLedgerError.eq
}

/-- [verified_ledger::{impl core::cmp::Eq for verified_ledger::LedgerError}::assert_fields_are_eq]:
    Source: 'src/lib.rs', lines 35:40-35:42
    Visibility: public -/
def LedgerError.Insts.CoreCmpEq.assert_fields_are_eq
  (self : LedgerError) : Result Unit := do
  ok ()

/-- Trait implementation: [verified_ledger::{impl core::cmp::Eq for verified_ledger::LedgerError}]
    Source: 'src/lib.rs', lines 35:40-35:42 -/
@[reducible]
def LedgerError.Insts.CoreCmpEq : core.cmp.Eq LedgerError := {
  partialEqInst := LedgerError.Insts.CoreCmpPartialEqLedgerError
  assert_fields_are_eq := LedgerError.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [verified_ledger::_::future]:
    Source: 'src/lib.rs', lines 45:0-45:77 -/
def anon.future {T : Type} (x : T) : Result (T × T) := do
  ok (x, x)

/-- [verified_ledger::_::ensures]:
    Source: 'src/lib.rs', lines 45:0-45:77 -/
def anon.ensures (accounts : Std.Usize) (l : Ledger) : Result Bool := do
  let s := alloc.vec.Vec.deref l.balances
  let i ← sum_balances s
  if i = l.total
  then ok (l.total = 0#u128)
  else ok false

/-- [verified_ledger::_]
    Source: 'src/lib.rs', lines 45:0-45:77 -/
@[global_simps, irreducible] def anon : Unit := ()

/-- [verified_ledger::new_ledger]:
    Source: 'src/lib.rs', lines 46:0-48:1
    Visibility: public -/
def new_ledger (accounts : Std.Usize) : Result Ledger := do
  let v ← alloc.vec.from_elem core.clone.CloneU64 0#u64 accounts
  ok { balances := v, total := 0#u128 }

/-- [verified_ledger::balance_of]:
    Source: 'src/lib.rs', lines 50:0-52:1
    Visibility: public -/
def balance_of
  (l : Ledger) (account : Std.Usize) : Result (Option Std.U64) := do
  let i := alloc.vec.Vec.len l.balances
  if account < i
  then
    let i1 ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice Std.U64)
        l.balances account
    ok (some i1)
  else ok none

/-- [verified_ledger::_#1::future]:
    Source: 'src/lib.rs', lines 55:0-59:7 -/
def __1.future {T : Type} (x : T) : Result (T × T) := do
  ok (x, x)

/-- [verified_ledger::_#1::ensures]:
    Source: 'src/lib.rs', lines 55:0-59:7 -/
def __1.ensures
  (l : Ledger) (to1 : Std.Usize) (amount : Std.U64)
  (p : (Ledger × (core.result.Result Unit LedgerError))) :
  Result Bool
  := do
  let (l2, r) := p
  let s := alloc.vec.Vec.deref l2.balances
  let i ← sum_balances s
  if i = l2.total
  then
    match r with
    | core.result.Result.Ok _ =>
      let i1 ← lift (UScalar.cast .U128 amount)
      let i2 ← l.total + i1
      ok (l2.total = i2)
    | core.result.Result.Err _ => Ledger.Insts.CoreCmpPartialEqLedger.eq l2 l
  else ok false

/-- [verified_ledger::_#1]
    Source: 'src/lib.rs', lines 55:0-59:7 -/
@[global_simps, irreducible] def __1 : Unit := ()

/-- [verified_ledger::mint]:
    Source: 'src/lib.rs', lines 60:0-73:1
    Visibility: public -/
def mint
  (l : Ledger) (to1 : Std.Usize) (amount : Std.U64) :
  Result (Ledger × (core.result.Result Unit LedgerError))
  := do
  let i := alloc.vec.Vec.len l.balances
  if to1 >= i
  then ok (l, core.result.Result.Err LedgerError.NoSuchAccount)
  else
    let i1 ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice Std.U64)
        l.balances to1
    let o ← lift (U64.checked_add i1 amount)
    match o with
    | none => ok (l, core.result.Result.Err LedgerError.BalanceOverflow)
    | some new =>
      let (_, index_mut_back) ←
        alloc.vec.Vec.index_mut (core.slice.index.SliceIndexUsizeSlice Std.U64)
          l.balances to1
      let i2 ← lift (UScalar.cast .U128 amount)
      let i3 ← l.total + i2
      let v := index_mut_back new
      ok ({ balances := v, total := i3 }, core.result.Result.Ok ())

/-- [verified_ledger::_#2::future]:
    Source: 'src/lib.rs', lines 76:0-80:7 -/
def __2.future {T : Type} (x : T) : Result (T × T) := do
  ok (x, x)

/-- [verified_ledger::_#2::ensures]:
    Source: 'src/lib.rs', lines 76:0-80:7 -/
def __2.ensures
  (l : Ledger) (from1 : Std.Usize) (amount : Std.U64)
  (p : (Ledger × (core.result.Result Unit LedgerError))) :
  Result Bool
  := do
  let (l2, r) := p
  let s := alloc.vec.Vec.deref l2.balances
  let i ← sum_balances s
  if i = l2.total
  then
    match r with
    | core.result.Result.Ok _ =>
      let i1 ← lift (UScalar.cast .U128 amount)
      let i2 ← l.total - i1
      ok (l2.total = i2)
    | core.result.Result.Err _ => Ledger.Insts.CoreCmpPartialEqLedger.eq l2 l
  else ok false

/-- [verified_ledger::_#2]
    Source: 'src/lib.rs', lines 76:0-80:7 -/
@[global_simps, irreducible] def __2 : Unit := ()

/-- [verified_ledger::burn]:
    Source: 'src/lib.rs', lines 81:0-94:1
    Visibility: public -/
def burn
  (l : Ledger) (from1 : Std.Usize) (amount : Std.U64) :
  Result (Ledger × (core.result.Result Unit LedgerError))
  := do
  let i := alloc.vec.Vec.len l.balances
  if from1 >= i
  then ok (l, core.result.Result.Err LedgerError.NoSuchAccount)
  else
    let i1 ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice Std.U64)
        l.balances from1
    let o ← lift (U64.checked_sub i1 amount)
    match o with
    | none => ok (l, core.result.Result.Err LedgerError.InsufficientFunds)
    | some new =>
      let (_, index_mut_back) ←
        alloc.vec.Vec.index_mut (core.slice.index.SliceIndexUsizeSlice Std.U64)
          l.balances from1
      let i2 ← lift (UScalar.cast .U128 amount)
      let i3 ← l.total - i2
      let v := index_mut_back new
      ok ({ balances := v, total := i3 }, core.result.Result.Ok ())

/-- [verified_ledger::_#3::future]:
    Source: 'src/lib.rs', lines 98:0-103:7 -/
def __3.future {T : Type} (x : T) : Result (T × T) := do
  ok (x, x)

/-- [verified_ledger::_#3::ensures]:
    Source: 'src/lib.rs', lines 98:0-103:7 -/
def __3.ensures
  (l : Ledger) (from1 : Std.Usize) (to1 : Std.Usize) (amount : Std.U64)
  (p : (Ledger × (core.result.Result Unit LedgerError))) :
  Result Bool
  := do
  let (l2, r) := p
  let s := alloc.vec.Vec.deref l2.balances
  let i ← sum_balances s
  if i = l2.total
  then
    if l2.total = l.total
    then
      match r with
      | core.result.Result.Ok _ => ok true
      | core.result.Result.Err _ => Ledger.Insts.CoreCmpPartialEqLedger.eq l2 l
    else ok false
  else ok false

/-- [verified_ledger::_#3]
    Source: 'src/lib.rs', lines 98:0-103:7 -/
@[global_simps, irreducible] def __3 : Unit := ()

/-- [verified_ledger::transfer]:
    Source: 'src/lib.rs', lines 104:0-132:1
    Visibility: public -/
def transfer
  (l : Ledger) (from1 : Std.Usize) (to1 : Std.Usize) (amount : Std.U64) :
  Result (Ledger × (core.result.Result Unit LedgerError))
  := do
  let i := alloc.vec.Vec.len l.balances
  if from1 >= i
  then ok (l, core.result.Result.Err LedgerError.NoSuchAccount)
  else
    let i1 := alloc.vec.Vec.len l.balances
    if to1 >= i1
    then ok (l, core.result.Result.Err LedgerError.NoSuchAccount)
    else
      let i2 ←
        alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice Std.U64)
          l.balances from1
      let o ← lift (U64.checked_sub i2 amount)
      match o with
      | none => ok (l, core.result.Result.Err LedgerError.InsufficientFunds)
      | some new_src =>
        if from1 = to1
        then ok (l, core.result.Result.Ok ())
        else
          let i3 ←
            alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice Std.U64)
              l.balances to1
          let o1 ← lift (U64.checked_add i3 amount)
          match o1 with
          | none => ok (l, core.result.Result.Err LedgerError.BalanceOverflow)
          | some new_dst =>
            let (_, index_mut_back) ←
              alloc.vec.Vec.index_mut (core.slice.index.SliceIndexUsizeSlice
                Std.U64) l.balances from1
            let v := index_mut_back new_src
            let (_, index_mut_back1) ←
              alloc.vec.Vec.index_mut (core.slice.index.SliceIndexUsizeSlice
                Std.U64) v to1
            let v1 := index_mut_back1 new_dst
            ok ({ l with balances := v1 }, core.result.Result.Ok ())

end verified_ledger
